events {
    worker_connections 1024;
}

http{
    server{
        listen 80;
        server_name localhost;
        include /etc/nginx/mime.types;

        location / {
            root /usr/share/nginx/html;
            index index.html;

            add_header X-Served-By $hostname always;
            add_header Cache-Control "no-store" always;
            ssi on;
        }

        location = /second {
            root /usr/share/nginx/html;
            try_files /second.html =404;
            add_header X-Served-By $hostname always;
            add_header Cache-Control "no-store" always;
            ssi on;
        }
    }
}
